=head1 NAME

Mini Scheme -- A science project

=head1 DESCRIPTION

Boot that REPL!!

  perl scheme.pl

=head1 BACKGROUND

This is for a science project that I am doing. The abstract of my project:

=over 2

B<Title>

Studying the effects of a syntactic analyzer on Scheme programs

B<Introduction>

In the MIT introductory book to computer programming, Structure and
Interpretation of Computer Programs, the outline for a simple Scheme
interpreter is given. In following sections, enhancements are made to
this interpreter. One of the most radical changes to the interpreter
is done by separating syntactic analysis of a Scheme expression from
the execution of the same. According to the authors, this greatly
improves execution times.

The purpose of this experiment is to study the effects of a syntactic
analyzer on run time. We believe that if a syntactic analyzer is used
before evaluation of Scheme code, a great increase in speed will be
observed.

=back

For the full, up-to-date lab report, see the doc/ directory in this
project.

=head1 KNOWN ISSUES

=over 4

=item *

CALL-WITH-CURRENT-CONTINUATION is non-existent.

=item *

No hygienic macro system.

=item *

The numeric tower is not implemented. All number types are snarfed directly from Perl.

=item *

STRING is a special form. This is purely for ease of implementation.

=item *

The following features are adapted from CMU Common Lisp:

=over 4

=item *

NIL is a symbol.

=back

=item *

No tail-call optimizations.

=item *

Next to no type checking.

=item *

Next to no error checking.

=back

=head1 FEATURES TO ADD

When I get around to it, I'll try to add these things in:

=over 4

=item *

A debugger. B<BIG> maybe.

=item *

CALL-WITH-CURRENT-CONTINUATION. I'll have to use Guy Steele's "LAMBDA: The Ultimate Declarative" a lot if I want to do this.

=back

=head1 BUGS

=over 4

=item *

Too slow. I'm looking for optimizations.

=item *

NIL really needs some clean-up.

=item *

No major bugs that I know of. Please see the L</KNOWN ISSUES> section
before reporting something that is wrong.

=back

=head1 AUTHOR

Ashton Wiersdorf <ashton.wiersdorf@mailblock.net>
